version: '3.8'
services:
  surreal:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: always
    # You can remove the memory option if you want to run the DB on disk
    command: start --log debug --user ${DATABASE_USER} --pass ${DATABASE_PASSWORD} file:/data/database.db
    ports:
      - '8000:8000'
    volumes:
      - surreal:/var/lib/surrealdb/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - surreal
    restart: always

volumes:
  surreal:
    driver: local
