version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@mongo:27017/

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8848:8848'
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local

networks:
  services:
    name: ${MONGO_NETWORK}